// Writes kiln-map/COUNT.md from the extracted items and the latest run log.
// This is the gate-1 report: for each core wood/soda source, did the run find
// the next firing (or confirm none is posted) and its registration status?
//
//   npm run kiln:count

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSources } from "./sources.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const DATA = join(ROOT, "data");
const TODAY = new Date().toISOString().slice(0, 10);
const IN_90 = new Date(Date.now() + 90 * 86400000).toISOString().slice(0, 10);
const YEAR_AGO = new Date(Date.now() - 365 * 86400000).toISOString().slice(0, 10);
const ATMOSPHERIC = ["wood", "soda", "salt"];
const REVIEW_FIELDS = ["title", "firing_type", "start_date", "end_date", "registration_status", "cost_text", "access_kind"];

const read = (f) => JSON.parse(readFileSync(f, "utf8"));
const list = (folder) => {
  const dir = join(DATA, folder);
  return existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => ({ folder, ...read(join(dir, f)) })) : [];
};

const sources = loadSources();
const pending = list("pending"), rejected = list("rejected");
const allApproved = list("approved");
const approved = allApproved.filter((i) => i.added_by !== "manual"); // hand-entered items don't count toward AI accuracy
const manual = allApproved.filter((i) => i.added_by === "manual");
const live = [...pending, ...allApproved];
const runs = existsSync(join(DATA, "runs")) ? readdirSync(join(DATA, "runs")).sort() : [];
// A partial run (--only=...) covers some sources, so use each source's most recent entry across all runs.
const latestBySource = new Map();
for (const f of runs) for (const entry of read(join(DATA, "runs", f)).sources) latestBySource.set(entry.id, entry);
const run = { sources: [...latestBySource.values()] };

const isAtmo = (i) => ATMOSPHERIC.includes(i.firing_type);
const dated = (i) => Boolean(i.start_date);
const upcoming = (i) => dated(i) && (i.end_date || i.start_date) >= TODAY;
const next90 = (i) => upcoming(i) && i.start_date <= IN_90;
const lastYear = (i) => dated(i) && i.start_date >= YEAR_AGO && i.start_date < TODAY;
const countBy = (items, key) => items.reduce((m, i) => ((m[i[key]] = (m[i[key]] || 0) + 1), m), {});
const cell = (t) => String(t ?? "").replace(/\|/g, "/");
const fmt = (m) => Object.entries(m).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(", ") || "none";

// Gate 1: per core source.
const coreRows = sources.filter((s) => s.core).map((s) => {
  const all = live.filter((i) => i.source_id === s.id);
  const items = all.filter((i) => i.added_by !== "manual"); // "kept up" measures the AI, not hand entries
  // The next firing is the earliest upcoming workshop/class/firing; residency start dates don't count.
  const known = (i) => i.registration_status !== "unknown" || Boolean(i.registration_opens);
  const firings = items.filter((i) => upcoming(i) && i.access_kind !== "residency").sort((a, b) => a.start_date.localeCompare(b.start_date));
  const next = firings.find(known) || firings[0];
  const ongoing = all.filter((i) => i.access_kind !== "dated");
  const r = run.sources.find((x) => x.id === s.id);
  const readable = r?.pages?.some((p) => p.chars > 200);
  const statusKnown = next ? known(next) : false;
  // "Kept up" = found the next firing with a status, or read the site fine and it lists no upcoming firing.
  const keptUp = next ? statusKnown : Boolean(readable) && items.length > 0;
  return { s, items, next, ongoing, r, readable, statusKnown, keptUp };
});
const keptUp = coreRows.filter((r) => r.keptUp).length;

// Review stats (approved items compared against the raw extraction).
const edited = approved.filter((i) => REVIEW_FIELDS.some((f) => JSON.stringify(i[f] ?? null) !== JSON.stringify(i._original?.[f] ?? null)));
const reviewed = approved.length + rejected.length;
const unchangedRate = reviewed ? Math.round(((approved.length - edited.length) / reviewed) * 100) : null;
const unverified = live.filter((i) => !i.quote_verified && i.added_by !== "manual");

const md = `# Firings count: ${TODAY}

Generated by \`npm run kiln:count\` from \`kiln-map/data/\` and each source's most recent run log. See the test in \`DESIGN-firings.md\` → Success Criteria.

## Gate 1: can AI keep up with the core wood/soda places?

**${keptUp} of ${coreRows.length} core sources kept up** (pass = at least 8, plus 80%+ of reviewed items approved unchanged).

| Source | Site readable? | Next firing found | Registration status | Ongoing routes in | Kept up? |
|---|---|---|---|---|---|
${coreRows.map(({ s, next, ongoing, r, readable, statusKnown, keptUp }) => {
  const site = !s.urls.length ? "no website" : readable ? "yes" : `no (${(r?.pages || []).map((p) => p.error || p.status).join(", ") || "not crawled"})`;
  const nx = next ? cell(`${next.start_date} ${next.title}`) : "none posted";
  const st = next ? (statusKnown ? cell(next.registration_status) + (next.registration_opens ? `, opens ${next.registration_opens}` : "") : "unknown") : "—";
  return `| ${s.org} | ${site} | ${nx} | ${st} | ${ongoing.map((o) => o.access_kind).join(", ") || "—"} | ${keptUp ? "yes" : "**no**"} |`;
}).join("\n")}

## Totals (pending + approved)

- **Next 90 days (${TODAY} → ${IN_90}):** ${live.filter(next90).length} dated (${fmt(countBy(live.filter(next90), "firing_type"))}). Wood/soda/salt: ${live.filter((i) => next90(i) && isAtmo(i)).length}.
- **Past 12 months:** ${live.filter(lastYear).length} dated (${fmt(countBy(live.filter(lastYear), "firing_type"))}). Wood/soda/salt: ${live.filter((i) => lastYear(i) && isAtmo(i)).length}.
- **Registration status of upcoming items:** ${fmt(countBy(live.filter(upcoming), "registration_status"))}.
- **Ongoing routes in:** ${fmt(countBy(live.filter((i) => i.access_kind !== "dated"), "access_kind"))}.
- **Crew calls:** ${live.filter((i) => i.crew_needed).length}.

## Review

- Pending ${pending.length}, approved ${approved.length} (${edited.length} edited), rejected ${rejected.length}, added by hand ${manual.length}.
- Rejection reasons: ${fmt(countBy(rejected, "reject_reason"))}.
- Edited: ${edited.map((i) => cell(i.title)).join("; ") || "none"}.
- Approved unchanged: ${unchangedRate === null ? "nothing reviewed yet" : `${unchangedRate}% of ${reviewed} reviewed`}.
- Items whose source quote was **not** found verbatim on the page: ${unverified.length}${unverified.length ? ` (${unverified.map((i) => i.id).join(", ")}). Check these first.` : "."}

## Every source in the last run

| Source | Pages read | Found | New | Changed | Notes |
|---|---|---|---|---|---|
${run.sources.map((r) => `| ${r.org} | ${(r.pages || []).filter((p) => p.chars > 200).length}/${(r.pages || []).length} | ${r.found} | ${r.written} | ${r.updated} | ${(r.notes || "").replace(/\|/g, "/").replace(/\n/g, " ")} |`).join("\n")}
`;

writeFileSync(join(ROOT, "COUNT.md"), md);
console.log(md);
