// Writes kiln-map/FOLLOW-UP.md: everything that needs a person, not the crawler.
//   1. Newsletters to join with kilns@flamingclay.com
//   2. Instagram: places where no handle was found (look one up; the crawl reads saved handles itself)
//   3. Reach out by email or phone, grouped by why:
//      blocks our crawler · on the map without proof from their own pages · no firing dates posted ·
//      removed but worth a call · no website or public contact
//   npm run kiln:followup
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSources, stateName } from "./sources.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const DATA = join(ROOT, "data");
const read = (f, fallback) => (existsSync(f) ? JSON.parse(readFileSync(f, "utf8")) : fallback);
const JOINED = new Set(["cobb-mountain", "burton-creek", "idyllwild-arts", "oribe-uncle-pauls", "sonoma-community-center", "verge-center", "artillery-ceramics", "mendocino-art-center", "manhattan-beach-art-center"]);

const sources = loadSources();
const site = read(join(ROOT, "..", "site", "data", "firings.json"), { places: [] });
const place = new Map(site.places.map((p) => [p.id, p]));
const health = read(join(DATA, "link-health.json"), {});
const signups = read(join(DATA, "signups.json"), {});
const removed = read(join(DATA, "removed-sources.json"), {});
const leads = read(join(DATA, "leads.json"), []);
const lastRun = new Map();
for (const f of existsSync(join(DATA, "runs")) ? readdirSync(join(DATA, "runs")).sort() : []) for (const e of read(join(DATA, "runs", f)).sources) lastRun.set(e.id, e);

const contactLine = (s) => {
  const c = s.contact || {};
  return [c.email && `email ${c.email}`, c.phone && `call ${c.phone}`, c.website && c.website, c.instagram && `@${c.instagram}`].filter(Boolean).join(" · ") || "no contact found";
};
const byState = (list) => [...list].sort((a, b) => stateName(a.state).localeCompare(stateName(b.state)) || a.org.localeCompare(b.org));
const item = (s, why) => `- [ ] **${s.org}** (${s.city}, ${s.state}). ${why} Contact: ${contactLine(s)}`;

// 1. Newsletters
const newsletters = byState(sources.filter((s) => s.newsletter_url && !JOINED.has(s.id)));
// 2. Instagram missing
const noIg = byState(sources.filter((s) => !s.contact?.instagram && s.urls.length));
// 3. Reach out
const blocked = byState(sources.filter((s) => {
  const r = lastRun.get(s.id);
  return health[s.id]?.status === "unclear" || (r && /No usable page text/.test(r.notes || ""));
}));
const unproven = byState(sources.filter((s) => {
  const p = place.get(s.id);
  return p && !blocked.includes(s) && s.urls.length && !p.opportunities.length && !(p.firing_evidence || []).length && !p.access;
}));
const noDates = byState(sources.filter((s) => {
  const p = place.get(s.id);
  return p && !blocked.includes(s) && !unproven.includes(s) && s.urls.length && !p.opportunities.length;
}));
const noContact = byState(sources.filter((s) => !s.urls.length));
const worthACall = byState(Object.values(removed).filter((s) => !/spam|closed|electric only|handbuilding only|sculpture workshops only|supply store|college pages only|institutional pages/i.test(s.removed_why || "")));

const L = [
  "# Follow-up list",
  "",
  `Everything that needs a person, not the crawler. Generated by \`npm run kiln:followup\` (${new Date().toISOString().slice(0, 10)}).`,
  "Tick items as you go; tell me what you learn and I'll update the places.",
  "",
  `## 1. Newsletters to join (${newsletters.length})`,
  "Sign up with **kilns@flamingclay.com**. The weekly crawl reads them automatically.",
  "",
  ...newsletters.map((s) => `- [ ] **${s.org}** (${s.city}, ${s.state}): ${s.newsletter_url}`),
  "",
  `## 2. Instagram handles to look up (${noIg.length})`,
  "No handle was found on their website. If they have one, tell me and I'll save it; the crawl then reads their posts. (Places with a saved handle need nothing from you.)",
  "",
  ...noIg.map((s) => `- [ ] **${s.org}** (${s.city}, ${s.state})`),
  "",
  "## 3. Reach out by email or phone",
  "",
  `### Their website blocks our crawler (${blocked.length})`,
  "We can't check them automatically. Ask: do you run firings outsiders can join, and where do you post dates?",
  "",
  ...blocked.map((s) => item(s, "Website blocks automatic checks.")),
  "",
  `### On the map without proof from their own pages (${unproven.length})`,
  "Kept because other reputable sources describe their kilns. Confirm the kilns and how outsiders get access.",
  "",
  ...unproven.map((s) => item(s, s.notes || "")),
  "",
  `### On the map, no firing dates posted (${noDates.length})`,
  "They have the kilns, but nothing to sign up for right now. Ask when the next firing or workshop is and how it's announced.",
  "",
  ...noDates.map((s) => item(s, s.access?.note || s.notes || "")),
  "",
  `### Removed for now, worth a call (${worthACall.length})`,
  "Their websites showed no joinable firings. Some may run them anyway. If yes, I'll add them back.",
  "",
  ...worthACall.map((s) => item(s, `Removed: ${s.removed_why}`)),
  "",
  `### Leads with no usable website (${leads.length})`,
  "Found in research but nothing we could crawl. Look them up or ask around; if they're real and joinable, I'll add them.",
  "",
  ...[...leads].sort((a, b) => a.state.localeCompare(b.state)).map((l) => `- [ ] **${l.org}** (${l.city}, ${l.state}). ${l.why}`),
  "",
  `### No website or public contact (${noContact.length})`,
  "Private kilns known from research. Ask around, or reach out through someone who's fired with them.",
  "",
  ...noContact.map((s) => item(s, s.notes || "")),
  "",
];
writeFileSync(join(ROOT, "FOLLOW-UP.md"), L.join("\n"));
console.log(`Wrote kiln-map/FOLLOW-UP.md: ${newsletters.length} newsletters, ${noIg.length} Instagram lookups, ${blocked.length + unproven.length + noDates.length + worthACall.length + noContact.length} places to reach out to.`);
