// Writes kiln-map/SIGNUPS.md: for every place, the newsletter to join with kilns@flamingclay.com and the
// Instagram handle the weekly crawl reads. Combines what's saved in the sources with what the latest crawl
// found on each place's pages (homepage included).
//   npm run kiln:signups            # write the list
//   npm run kiln:signups -- --apply # also save newly found Instagram handles / newsletter links into the sources
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSources, saveSources, stateName } from "./sources.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const APPLY = process.argv.includes("--apply");
// Robby joined these newsletters on 2026-10-05 (kiln-map/NEWSLETTERS.md).
const JOINED = new Set(["cobb-mountain", "burton-creek", "idyllwild-arts", "oribe-uncle-pauls", "sonoma-community-center", "verge-center", "artillery-ceramics", "mendocino-art-center", "manhattan-beach-art-center"]);

const file = join(ROOT, "data", "signups.json");
const latest = new Map(Object.entries(existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : {}));

const norm = (s) => (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
// Pick the handle that looks like the place's own account (pages also link to partners and artists).
function bestHandle(source, handles) {
  if (!handles.length) return null;
  const org = norm(source.org), host = norm((() => { try { return new URL(source.contact?.website || source.urls[0]).hostname.replace(/^www\./, "").split(".")[0]; } catch { return ""; } })());
  const score = (h) => { const n = norm(h); return (host && (n.includes(host) || host.includes(n)) ? 3 : 0) + (org.includes(n) || n.includes(org.slice(0, 8)) ? 2 : 0); };
  const ranked = [...handles].sort((a, b) => score(b) - score(a));
  return score(ranked[0]) > 0 || handles.length === 1 ? ranked[0] : null;
}

const sources = loadSources();
let changed = 0;
const byState = new Map();
for (const s of sources) {
  const found = latest.get(s.id) || { instagram: [], newsletter: [] };
  const ig = s.contact?.instagram || bestHandle(s, found.instagram);
  const nl = s.newsletter_url || found.newsletter[0] || null;
  if (APPLY) {
    if (!s.contact?.instagram && ig) { s.contact = { ...(s.contact || {}), instagram: ig }; changed++; }
    if (!s.newsletter_url && nl && !/sign-up form on this page/.test(nl)) { s.newsletter_url = nl; changed++; }
    if (!s.newsletter_url && nl && /sign-up form on this page/.test(nl)) { s.newsletter_url = nl.replace(/ \(sign-up form on this page\)$/, ""); changed++; }
  }
  if (!byState.has(s.state)) byState.set(s.state, []);
  byState.get(s.state).push({ s, ig, nl, joined: JOINED.has(s.id), otherIg: found.instagram.filter((h) => h !== ig).slice(0, 4) });
}
if (APPLY && changed) saveSources(sources);

const lines = [
  "# Newsletters to join and Instagram accounts the crawl reads",
  "",
  "Sign up with **kilns@flamingclay.com**. Instagram handles need nothing from you: the weekly crawl reads them through",
  "your token. Places marked ✅ you've already joined. Generated by `npm run kiln:signups`.",
  "",
];
let todo = 0;
for (const state of [...byState.keys()].sort((a, b) => stateName(a).localeCompare(stateName(b)))) {
  lines.push(`## ${stateName(state)}`, "");
  for (const { s, ig, nl, joined, otherIg } of byState.get(state).sort((a, b) => a.s.org.localeCompare(b.s.org))) {
    const news = nl ? (joined ? `✅ joined` : `[ ] join: ${nl.replace(/ \(sign-up form on this page\)$/, "")}${/sign-up form/.test(nl) ? " (form on the page)" : ""}`) : "no newsletter found";
    if (nl && !joined) todo++;
    lines.push(`- **${s.org}** (${s.city}). Newsletter: ${news}. Instagram: ${ig ? `@${ig}` : "none found"}${otherIg.length ? ` (page also links @${otherIg.join(", @")})` : ""}`);
  }
  lines.push("");
}
lines.splice(4, 0, `**${todo} newsletters still to join.**`, "");
writeFileSync(join(ROOT, "SIGNUPS.md"), lines.join("\n"));
console.log(`Wrote kiln-map/SIGNUPS.md (${todo} newsletters to join)${APPLY ? `; saved ${changed} new handles/links to the sources` : ""}.`);
